import heapq
a = []   #创建一个空堆
heapq.heappush(a,(5,'B'))
heapq.heappush(a,(7,'A'))
heapq.heappush(a,(9,'C'))
print(a)
a1=heapq.heappop(a)
print(a1)
heapq.heappush(a,(6,'A'))
heapq.heappush(a,(10,'D'))
print(a)
a2=heapq.heappop(a)
print(a2)
heapq.heappush(a,(11,'T'))
a3=heapq.heappop(a)
print(a3)
heapq.heappush(a,(11,'F'))
print(a)
heapq.heappop(a)
print(a)
heapq.heappush(a,(12,'G'))
print(a)
heapq.heappop(a)
print(a)
heapq.heappop(a)
print(a)
heapq.heappop(a)
print(a)